services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    command: ["npm", "run", "dev"]


  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: App_Taxi
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"  #Porta padrão 3307
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  mysql-data:

networks:
  backend_network:
    driver: bridge
