services:
  frontend:
    build:
      context: ./frontend # Caminho para o diretório do front-end
    ports:
      - "80:80" # Mapeia a porta 3000 do container para a 3000 do host
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: App_Taxi
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  mysql-data:

networks:
  backend_network:
    driver: bridge
